#!/bin/sh
# sshatest

program=$(basename $0)
dir=$(dirname $0)

# This script assumes that ssha is in the same directory
ssha=$dir/ssha
sshafuncs=$dir/ssha.funcs

. $sshafuncs

if ssh_ready; then
    echo 1>&2 "ready for ssh operations such as ssh, scp, rsync..."
else
    echo 1>&2 "error: unable to setup the ssh-agent"
    exit 1
fi
